version: '2'
networks: 
  consul_network: 
services:
 consul:
  image: consul
  ports:
  - "8300-8302:8300-8302" 
  - "8400:8400"
  - "8301-8302:8301-8302/udp"
  - "8600:8600"
  - "8600:8600/udp"
  - "8500:8500" 
  network_mode: host
 registrator:
  image: gliderlabs/registrator:latest    
  depends_on:
  - consul
  entrypoint: /bin/registrator consul://localhost:8500
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  network_mode: host
 msortweb:
  build: .
  image: goarne/msortweb:latest
  ports: 
   - "8081:8081"
  network_mode: host